plugins:
  - displayName: Plugin 1
    command: bash
    args:
      - -c
      - echo -n plugin-1
    showInSubMenu: true
  - displayName: Plugin 2
    command: bash
    args:
      - -c
      - echo -n plugin-2
