on: [push, pull_request]

name: Continuous integration

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v1
        with:
          name: bitbar-composite-plugin-${{runner.os}}-${{github.sha}}
          path: ./target/release/bitbar-composite-plugin

  publish:
    name: Publish to Bintray
    runs-on: ubuntu-18.04
    needs: ci
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v1
      with:
        name: bitbar-composite-plugin-Linux-${{github.sha}}
        path: ./bin

    - name: Download MacOS artifact
      uses: actions/download-artifact@v1
      with:
        name: bitbar-composite-plugin-Linux-${{github.sha}}
        path: ./bin

    - name: List downloaded artifacts
      run: ls -la ./bin

    - name: Upload to Bintray
      uses: hpcsc/upload-bintray-docker-action@v1
      with:
        repository: bitbar-composite-plugin
        package: master
        version: ${{github.sha}}
        sourcePath: ./bin/bitbar-composite-plugin*
        username: hpcsc
        apiKey: ${{secrets.BINTRAY_API_KEY}}
